### ISSUE TITLE
Use case: chaining & collecting

### ISSUE THREAD

**Issue by tbreuss** [Aaronmacaron/reaction#2]
Great little package, thanks!

I was wondering if the following is a valid use case for this package.

```php
<?php

use Aaronmacaron\Reaction\Reaction;

include __DIR__ . "/vendor/autoload.php";

function validatePassword(string $password): Reaction
{
    if (empty($password)) {
        return Reaction::failure("The password must not be empty!");
    }
    if (strlen($password) >= 8) {
        return Reaction::success();
    }
    return Reaction::failure("The password must be at least eight chars long.");
}

function validateFoo(): Reaction
{
    return Reaction::failure("Foo failure");
}

function validateBar(): Reaction
{
    return Reaction::success("Bar success");
}

$succeed = [];
$errors = [];

validatePassword("secret")
    ->succeed(function () use (&$succeed) {
        $succeed[] = "Password is valid";
    })->fail(function (Reaction $reaction) use (&$errors) {
        $errors[] = "The password is not valid: " . $reaction->getMessage();
    });

validateFoo()->fail(function (Reaction $reaction) use (&$errors) {
    $errors[] = $reaction->getMessage();
});

validateBar()->succeed(function (Reaction $reaction) use (&$succeed) {
    $succeed[] = $reaction->getMessage();
});

echo "<pre>";
print_r($succeed);
print_r($errors);
echo "</pre>";
```

You get the idea? I'm talking about chaining and collecting Reactions.

[And sorry for the quick'n'dirty code posting.]

**Comment by Aaronmacaron** [comment]
Yes I see what you're saying. Maybe we could add a mechanism to support this kind of handling multiple reactions natively. I was thinking about something like that:

```php
<?php

use Aaronmacaron\Reaction\Reaction;

include __DIR__ . "/vendor/autoload.php";

function validatePassword(string $password): Reaction
{
    if (empty($password)) {
        return Reaction::failure("The password must not be empty!");
    }
    if (strlen($password) >= 8) {
        return Reaction::success();
    }
    return Reaction::failure("The password must be at least eight chars long.");
}

function validateFoo(): Reaction
{
    return Reaction::failure("Foo failure");
}

function validateBar(): Reaction
{
    return Reaction::success("Bar success");
}

$reactions = [
    validatePassword("secret"),
    validateFoo(),
    validateBar(),
];

Reaction::all($reactions)->succeed(function (array $messages) {
    echo "Successes:" . PHP_EOL;
    echo join(PHP_EOL, $messages);
})->fail(function (array $messages) {
    echo "Failures:" . PHP_EOL;
    echo join(PHP_EOL, $messages);
});
```
What do you think about this approach?

**Comment by tbreuss** [comment]
Good idea. But it depends on what you're trying to achieve. 

Do you want to display all successes and/or failures in a DIV in your HTML code? 
--> Go for this solution

Do you want to display these reactions near certain fields identified by IDs or names?
--> Not possible with this approach

**Comment by Aaronmacaron** [comment]
I think it is important to have a very flexible solution that can be used for a variety of different use cases. So maybe my proposed solution is not suitable enough. What kind of solution would you suggest then?

**Comment by tbreuss** [comment]
After thinking a while I suggest to wait until we have a real use case. Without it is likely to end in a feature that nobody needs. What do you think?

You can close the issue, if okay for you.

**Comment by Aaronmacaron** [comment]
I think this is a good decision to make. There is no point in implementing a feature that nobody's going ever to use and clutters the project. I'll close this issue.
